-- Criação da Tabela: Dicas
CREATE TABLE dicas (
    id_dicas SERIAL PRIMARY KEY,
    titulo_dicas VARCHAR(200),
    descricao_dicas VARCHAR(1000),
);

-- Inserções das Dicas
INSERT INTO dicas (titulo_dicas, descricao_dicas) VALUES
('Dica Número 01: Planeje sua Rotina', 'Ter um bom plano para o seu dia é essencial, seja para passar no vestibular ou melhorar suas habilidades profissionais. Organizar o tempo de forma que você consiga estudar sem abrir mão de outras tarefas é o primeiro passo. Divida seu tempo de maneira equilibrada, estabeleça metas realistas para o que você vai estudar e não esqueça de reservar um tempo para descanso e lazer. Assim, você garante produtividade sem estresse excessivo.'),
('Dica Número 02: Crie o Hábito de Estudar', 'Planejar é importante, mas o verdadeiro progresso vem com a prática diária. Criar o hábito de estudar regularmente, mesmo que por pouco tempo, ajuda a consolidar o que você aprende. Estabeleça um horário fixo, escolha um ambiente tranquilo e mantenha a consistência. No início, pode ser difícil, mas com o tempo, estudar vai se tornar parte natural da sua rotina. Só lembre-se de equilibrar os estudos com momentos de lazer para evitar o desgaste.'),
('Dica Número 03: Revise o Conteúdo Diariamente', 'Revisar é uma das melhores formas de fixar o conteúdo. Quando você revê o que aprendeu, seu cérebro assimila melhor as informações e identifica os pontos que precisam de mais atenção. Dedique ao menos 10 a 15 minutos do seu dia para revisar as matérias, seja relendo anotações, refazendo exercícios ou até explicando o que aprendeu para alguém. Isso vai tornar o processo de aprendizado mais sólido e contínuo.'),
('Dica Número 04: Faça Exercícios e Pratique', 'Estudar a teoria é só metade do caminho. Praticar o que você aprendeu é essencial para entender de verdade os conceitos. Resolva exercícios, participe de simulados e busque aplicar o que aprendeu em situações práticas, como projetos ou problemas do dia a dia. Isso não só ajuda a fixar o conteúdo, mas também te prepara para desafios futuros e para aplicar esse conhecimento em contextos reais.'),
('Dica Número 05: Mantenha-se Atualizado', 'O mundo está em constante mudança, e as áreas de estudo e mercado de trabalho evoluem junto. Por isso, além de estudar os conteúdos base, é importante estar sempre de olho nas novidades. Acompanhe notícias, leia artigos e participe de eventos ou cursos online que estejam alinhados com seus interesses. Isso vai te ajudar a estar sempre à frente e preparado para novas oportunidades.'),
('Dica Número 06: Encontre uma Rede de Apoio', 'Estudar sozinho pode ser desafiador, e é aí que uma boa rede de apoio entra. Trocar ideias com amigos, colegas ou professores pode te ajudar a entender melhor os conteúdos e a manter a motivação. Participar de grupos de estudo, por exemplo, é uma ótima forma de aprender com os outros e ainda ajudar quem está com dificuldade. Além disso, um mentor ou alguém com mais experiência pode oferecer insights valiosos para o seu crescimento.'),
('Dica Número 07: Cuide da sua Saúde Mental e Física', 'Nenhum esforço vale a pena se a sua saúde estiver comprometida. Equilibrar os estudos com uma boa alimentação, exercício físico e momentos de lazer é essencial para manter o corpo e a mente funcionando bem. Se sentir exausto ou desmotivado é normal de vez em quando, mas é importante reconhecer quando parar e descansar. Tirar um tempo para si mesmo vai te ajudar a voltar aos estudos com mais foco e energia.');